export const READY_TO_BUY_CATEGORIES = [
  { id: 'all', label: 'All Products', icon: '✨' },
  { id: 'tshirts', label: 'T-Shirts', icon: '👕' },
  { id: 'polo', label: 'Polo Shirts', icon: '👔' },
  { id: 'oversized', label: 'Oversized', icon: '⚡' },
  { id: 'hoodies', label: 'Hoodies', icon: '🧥' },
  { id: 'aprons', label: 'Aprons', icon: '🍳' },
  { id: 'mugs', label: 'Mugs', icon: '☕' },
  { id: 'caps', label: 'Caps', icon: '🧢' },
  { id: 'badges', label: 'Badges & Pins', icon: '🎖️' },
];

export const READY_TO_BUY_COLLECTIONS = [
  'All Collections',
  'Streetwear',
  'Anime & Manga',
  'Cyberpunk 2099',
  'Minimalist & Typography',
  'Sports & Fitness',
  'Corporate & Executive',
  'Vintage Retro',
  'Gaming & Tech',
];

export const READY_TO_BUY_PRINT_TYPES = [
  'HD Direct-to-Film (DTF)',
  'High-Density 3D Embroidery',
  'All-Over HD Sublimation',
  'Premium Screen Printing',
];

export const READY_TO_BUY_PRODUCTS = [
  {
    id: 'rtb-cyberpunk-oversized-tee',
    name: 'Cyberpunk Neo-Tokyo 2099 Oversized T-Shirt',
    slug: 'cyberpunk-neo-tokyo-2099-oversized-tshirt',
    category: 'Oversized',
    categoryKey: 'oversized',
    designName: 'Neo-Tokyo Cybernetic Samurai',
    description: 'Ultra-heavyweight 240 GSM 100% French Terry loopknit cotton with high-density HD-DTF curing. Features a futuristic Neo-Tokyo cybernetic samurai artwork on front and back statement kanji typography.',
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    price: 699,
    compareAtPrice: 999,
    colors: [
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'Pure White', hex: '#f8fafc' },
      { name: 'Acid Charcoal', hex: '#334155' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    defaultSize: 'L',
    defaultColor: 'Obsidian Black',
    printMethod: 'HD Direct-to-Film (DTF)',
    stock: 45,
    sku: 'PH-RTB-CPK-01',
    tags: ['Cyberpunk', 'Streetwear', 'Oversized', 'Anime', 'Neo Tokyo'],
    collection: 'Cyberpunk 2099',
    rating: 4.9,
    reviewCount: 148,
    badge: 'BEST SELLER',
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-retro-synthwave-tee',
    name: 'Retro Synthwave Sunset Horizon Regular T-Shirt',
    slug: 'retro-synthwave-sunset-horizon-tshirt',
    category: 'T-Shirts',
    categoryKey: 'tshirts',
    designName: '80s Synthwave Grid Neon Sunset',
    description: '180 GSM bio-washed combed cotton with ultra-soft breathable feel. High-definition 8-color gradient screen print that never fades, crackles or peels.',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    ],
    price: 499,
    compareAtPrice: 799,
    colors: [
      { name: 'Midnight Navy', hex: '#0f172a' },
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'French Grey', hex: '#94a3b8' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    defaultSize: 'M',
    defaultColor: 'Midnight Navy',
    printMethod: 'HD Direct-to-Film (DTF)',
    stock: 62,
    sku: 'PH-RTB-RETRO-02',
    tags: ['Synthwave', 'Vintage', 'Retro 80s', 'T-Shirt', 'Graphic'],
    collection: 'Vintage Retro',
    rating: 4.8,
    reviewCount: 92,
    badge: 'TRENDING',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-tokyo-underground-hoodie',
    name: 'Tokyo Underground Streetwear Heavyweight Hoodie',
    slug: 'tokyo-underground-streetwear-heavyweight-hoodie',
    category: 'Hoodies',
    categoryKey: 'hoodies',
    designName: 'Shibuya Midnight Shift Illustration',
    description: '380 GSM brushed fleece with double-lined thermal hood, heavy-duty ribbed cuffs and kangaroo pouch. Custom chest graphic and sleeve statement typography.',
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=800&q=80',
    ],
    price: 1299,
    compareAtPrice: 1899,
    colors: [
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'Heather Charcoal', hex: '#334155' },
      { name: 'Forest Green', hex: '#14532d' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    defaultSize: 'XL',
    defaultColor: 'Obsidian Black',
    printMethod: 'HD Direct-to-Film (DTF)',
    stock: 28,
    sku: 'PH-RTB-HD-03',
    tags: ['Hoodie', 'Streetwear', 'Tokyo', 'Heavyweight', 'Fleece'],
    collection: 'Streetwear',
    rating: 5.0,
    reviewCount: 215,
    badge: 'TOP RATED',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-executive-crest-polo',
    name: 'Executive Crest Monogram Pique Polo Shirt',
    slug: 'executive-crest-monogram-pique-polo',
    category: 'Polo Shirts',
    categoryKey: 'polo',
    designName: 'Minimalist Laurel Wreath Monogram',
    description: '220 GSM 100% Matty Pique Cotton with knitted collar and 3-button placket. Features luxury 12,000-stitch high-density 3D embroidery on left chest.',
    images: [
      'https://images.unsplash.com/photo-1625910513413-5bc25e656d29?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    price: 749,
    compareAtPrice: 1099,
    colors: [
      { name: 'Midnight Navy', hex: '#0f172a' },
      { name: 'Pure White', hex: '#f8fafc' },
      { name: 'Burgundy Wine', hex: '#4c0519' },
    ],
    sizes: ['M', 'L', 'XL', '2XL', '3XL'],
    defaultSize: 'L',
    defaultColor: 'Midnight Navy',
    printMethod: 'High-Density 3D Embroidery',
    stock: 35,
    sku: 'PH-RTB-POLO-04',
    tags: ['Polo', 'Corporate', 'Embroidery', 'Executive', 'Luxury'],
    collection: 'Corporate & Executive',
    rating: 4.9,
    reviewCount: 84,
    badge: 'POPULAR',
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-barista-heavy-apron',
    name: 'Master Craftsman Heavy Canvas Kitchen & Barista Apron',
    slug: 'master-craftsman-heavy-canvas-barista-apron',
    category: 'Aprons',
    categoryKey: 'aprons',
    designName: 'Artisan Roaster Vintage Crest',
    description: '16oz heavy waxed cotton canvas with genuine leather straps, brass buckles, and dual utility pockets. Precision embroidered craftsman badge.',
    images: [
      'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    ],
    price: 849,
    compareAtPrice: 1299,
    colors: [
      { name: 'Raw Tan Sandstone', hex: '#d6c7b2' },
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'Deep Olive', hex: '#14532d' },
    ],
    sizes: ['Universal Adjustable'],
    defaultSize: 'Universal Adjustable',
    defaultColor: 'Raw Tan Sandstone',
    printMethod: 'High-Density 3D Embroidery',
    stock: 19,
    sku: 'PH-RTB-APRN-05',
    tags: ['Apron', 'Barista', 'Chef', 'Craftsman', 'Canvas'],
    collection: 'Minimalist & Typography',
    rating: 4.8,
    reviewCount: 56,
    badge: 'LIMITED',
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-astronaut-cosmic-mug',
    name: 'Deep Space Astronaut 11oz Ceramic Coffee Mug',
    slug: 'deep-space-astronaut-11oz-ceramic-mug',
    category: 'Mugs',
    categoryKey: 'mugs',
    designName: 'Lost in Andromeda Cosmic Explorer',
    description: 'Grade-A glossy ceramic with 360-degree all-over sublimation print. Microwave and dishwasher safe, vibrant scratch-proof ceramic glaze.',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=800&q=80',
    ],
    price: 299,
    compareAtPrice: 499,
    colors: [
      { name: 'Glossy White Inside', hex: '#ffffff' },
      { name: 'Midnight Black Rim', hex: '#121214' },
    ],
    sizes: ['11oz (325ml) Standard'],
    defaultSize: '11oz (325ml) Standard',
    defaultColor: 'Glossy White Inside',
    printMethod: 'All-Over HD Sublimation',
    stock: 75,
    sku: 'PH-RTB-MUG-06',
    tags: ['Mug', 'Space', 'Astronaut', 'Coffee', 'Ceramic'],
    collection: 'Gaming & Tech',
    rating: 4.9,
    reviewCount: 172,
    badge: 'BEST SELLER',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-embroidered-urban-cap',
    name: 'Urban Cyberpunk Kanji Embroidered Dad Cap',
    slug: 'urban-cyberpunk-kanji-embroidered-dad-cap',
    category: 'Caps',
    categoryKey: 'caps',
    designName: 'Neo Tokyo 3D Relief Kanji Emblem',
    description: '100% structured twill cotton with pre-curved visor, breathable eyelets, and adjustable brass buckle strap. High-relief 3D embroidery.',
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    price: 449,
    compareAtPrice: 699,
    colors: [
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'Charcoal Grey', hex: '#334155' },
      { name: 'Pure White', hex: '#f8fafc' },
    ],
    sizes: ['Free Size (Adjustable)'],
    defaultSize: 'Free Size (Adjustable)',
    defaultColor: 'Obsidian Black',
    printMethod: 'High-Density 3D Embroidery',
    stock: 31,
    sku: 'PH-RTB-CAP-07',
    tags: ['Cap', 'Streetwear', 'Embroidery', 'Kanji', 'Hat'],
    collection: 'Streetwear',
    rating: 4.8,
    reviewCount: 68,
    badge: 'TRENDING',
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-anime-enamel-badges-set',
    name: 'Cyberpunk & Anime Aesthetic Metallic Pin Badges (Pack of 4)',
    slug: 'cyberpunk-anime-metallic-pin-badges-pack',
    category: 'Badges & Pins',
    categoryKey: 'badges',
    designName: 'Neo Icons Metallic Pins Collector Set',
    description: '58mm gloss-laminated stainless steel pin-back buttons. Mylar coated waterproof surface with safety pin mechanism for jackets, backpacks and hats.',
    images: [
      'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
    ],
    price: 199,
    compareAtPrice: 349,
    colors: [
      { name: 'Multicolor Pack', hex: '#6366f1' },
    ],
    sizes: ['58mm Round (Set of 4)'],
    defaultSize: '58mm Round (Set of 4)',
    defaultColor: 'Multicolor Pack',
    printMethod: 'All-Over HD Sublimation',
    stock: 90,
    sku: 'PH-RTB-BDG-08',
    tags: ['Badges', 'Pins', 'Anime', 'Cyberpunk', 'Collectible'],
    collection: 'Anime & Manga',
    rating: 4.9,
    reviewCount: 110,
    badge: 'NEW',
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-matrix-code-oversized-tee',
    name: 'Terminal Matrix Glitch Code Oversized Streetwear T-Shirt',
    slug: 'terminal-matrix-glitch-code-oversized-tshirt',
    category: 'Oversized',
    categoryKey: 'oversized',
    designName: 'Digital Rain Terminal Monospace',
    description: '240 GSM drop shoulder loopknit cotton with vivid neon cyber green DTF print on matte obsidian cotton. Reinforced collar ribbing that retains structure wash after wash.',
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
    ],
    price: 699,
    compareAtPrice: 999,
    colors: [
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'Charcoal', hex: '#334155' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    defaultSize: 'L',
    defaultColor: 'Obsidian Black',
    printMethod: 'HD Direct-to-Film (DTF)',
    stock: 38,
    sku: 'PH-RTB-MTX-09',
    tags: ['Hacker', 'Matrix', 'Oversized', 'Streetwear', 'Tech'],
    collection: 'Gaming & Tech',
    rating: 4.9,
    reviewCount: 76,
    badge: 'TRENDING',
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-mount-fuji-hoodie',
    name: 'Mount Fuji Sunset Cherry Blossom Heavyweight Hoodie',
    slug: 'mount-fuji-sunset-cherry-blossom-hoodie',
    category: 'Hoodies',
    categoryKey: 'hoodies',
    designName: 'Ukiyo-e Japanese Woodblock Aesthetic',
    description: '380 GSM heavyweight brushed fleece with double-lined hood. High-resolution gradient back print depicting traditional Mount Fuji with modern minimalist streetwear flair.',
    images: [
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
    ],
    price: 1349,
    compareAtPrice: 1999,
    colors: [
      { name: 'Dusty Lavender', hex: '#c084fc' },
      { name: 'Pure White', hex: '#f8fafc' },
      { name: 'Obsidian Black', hex: '#121214' },
    ],
    sizes: ['M', 'L', 'XL', '2XL'],
    defaultSize: 'L',
    defaultColor: 'Dusty Lavender',
    printMethod: 'HD Direct-to-Film (DTF)',
    stock: 22,
    sku: 'PH-RTB-FUJI-10',
    tags: ['Japanese', 'Anime', 'Fuji', 'Hoodie', 'Aesthetic'],
    collection: 'Anime & Manga',
    rating: 5.0,
    reviewCount: 164,
    badge: 'BEST SELLER',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-zen-minimal-tee',
    name: 'Zen Geometry Minimalist Circle Regular T-Shirt',
    slug: 'zen-geometry-minimalist-circle-tshirt',
    category: 'T-Shirts',
    categoryKey: 'tshirts',
    designName: 'Enso Japanese Zen Circle & Geometric Lines',
    description: '180 GSM combed cotton with subtle monochrome chest print. Perfect balance of Eastern mindfulness philosophy and contemporary clean aesthetics.',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    ],
    price: 449,
    compareAtPrice: 699,
    colors: [
      { name: 'Pure White', hex: '#f8fafc' },
      { name: 'Obsidian Black', hex: '#121214' },
      { name: 'Warm Sandstone', hex: '#d6c7b2' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    defaultSize: 'M',
    defaultColor: 'Pure White',
    printMethod: 'HD Direct-to-Film (DTF)',
    stock: 54,
    sku: 'PH-RTB-ZEN-11',
    tags: ['Minimalist', 'Zen', 'Geometry', 'Clean', 'T-Shirt'],
    collection: 'Minimalist & Typography',
    rating: 4.7,
    reviewCount: 43,
    badge: 'POPULAR',
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    isCustomizable: false,
    status: 'published',
  },
  {
    id: 'rtb-developer-code-mug',
    name: 'Eat Sleep Code Repeat 11oz Developer Ceramic Mug',
    slug: 'eat-sleep-code-repeat-11oz-developer-mug',
    category: 'Mugs',
    categoryKey: 'mugs',
    designName: 'Syntax Highlighted Full-Stack Flowchart',
    description: 'Premium heavy ceramic coffee cup with glossy glaze and crisp VS Code dark theme syntax highlighting. The ultimate desk companion for software engineers.',
    images: [
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ],
    price: 299,
    compareAtPrice: 499,
    colors: [
      { name: 'Obsidian Black Gloss', hex: '#121214' },
      { name: 'Pure White Gloss', hex: '#ffffff' },
    ],
    sizes: ['11oz (325ml) Standard'],
    defaultSize: '11oz (325ml) Standard',
    defaultColor: 'Obsidian Black Gloss',
    printMethod: 'All-Over HD Sublimation',
    stock: 82,
    sku: 'PH-RTB-MUG-12',
    tags: ['Developer', 'Coding', 'Mug', 'Office', 'Gift'],
    collection: 'Gaming & Tech',
    rating: 4.9,
    reviewCount: 135,
    badge: 'BEST SELLER',
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    isCustomizable: false,
    status: 'published',
  },
];
